version: "3.9"
services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src/
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db_data:/etc/mongo
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
